"""
Lease Abstract Compendium builder (.docx) — per-property, per-tenancy,
generated from the VERIFIED KA portfolio warehouse (page-cited provisions)
plus the canonical rent-roll module for point-in-time economics.

Style follows the Southtown compendium precedent (KA navy/red, provenance
banner, page-numbered footer). Every provision carries its source + page
citation; refi-impact provisions are flagged. Nothing is generated by a
language model at build time — this document renders verified data only.
"""

import datetime
import os
import re

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

KA_NAVY = RGBColor(0x1B, 0x2A, 0x4A)
KA_RED = RGBColor(0xC8, 0x10, 0x2E)
KA_BLUE = RGBColor(0x2E, 0x5A, 0x88)
GREY = RGBColor(0x60, 0x6A, 0x78)
NAVY_FILL = "1B2A4A"
CLOUD_FILL = "EEF3F8"
RED_FILL = "FBEAEC"


_CTRL = re.compile(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]')


def _clean(s):
    """XML-safe text: strip control characters OCR sometimes leaves behind."""
    return _CTRL.sub('', s) if isinstance(s, str) else s


def _shade(cell, fill):
    tcpr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:fill"), fill)
    tcpr.append(shd)


def _footer(section, label):
    p = section.footer.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(f"CONFIDENTIAL — {label}     ·     Page ")
    run.font.size = Pt(8)
    run.font.color.rgb = GREY
    fld = OxmlElement("w:fldSimple")
    fld.set(qn("w:instr"), "PAGE")
    p._p.append(fld)


def _center_line(doc, text, size, color, bold=True, after=2, upper=False):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_after = Pt(after)
    r = p.add_run(text.upper() if upper else text)
    r.bold = bold
    r.font.size = Pt(size)
    r.font.color.rgb = color
    return p


def _red_rule(doc):
    rule = doc.add_paragraph()
    rule.paragraph_format.space_before = Pt(8)
    pborders = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "18")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "C8102E")
    pborders.append(bottom)
    rule._p.get_or_add_pPr().append(pborders)


def _kv_table(doc, pairs, col0=1.7, col1=4.8):
    tbl = doc.add_table(rows=0, cols=2)
    tbl.style = "Table Grid"
    tbl.autofit = False
    for label, value in pairs:
        cells = tbl.add_row().cells
        cells[0].width = Inches(col0)
        cells[1].width = Inches(col1)
        _shade(cells[0], CLOUD_FILL)
        r0 = cells[0].paragraphs[0].add_run(label)
        r0.bold = True
        r0.font.size = Pt(9)
        r1 = cells[1].paragraphs[0].add_run('—' if value in (None, '') else _clean(str(value)))
        r1.font.size = Pt(9.5)
    return tbl


def _fmt_money(v):
    try:
        return f"${float(v):,.2f}"
    except (TypeError, ValueError):
        return None


def _fmt_sf(v):
    try:
        return f"{float(v):,.0f} SF"
    except (TypeError, ValueError):
        return None


def _refi_flagged(p):
    r = (p.get('refi_impact') or '').strip()
    return bool(r) and r.lower() not in ('none', 'n/a', 'no', '-')


def build_compendium(data, out_path, mode='full'):
    """mode='full': every provision rendered verbatim (exhaustive record).
    mode='summary': tenancy summaries + a compact provision index per
    tenancy (category, refi flag, citation) — the briefing-length cut."""
    prop = data['property']
    tenancies = data['tenancies']
    pname = prop.get('property_name') or prop.get('property_key')
    today = datetime.date.today().isoformat()

    doc = Document()
    doc.styles["Normal"].font.name = "Calibri"
    doc.styles["Normal"].font.size = Pt(10)

    # ── Title block ──
    _center_line(doc, "KRAUS-ANDERSON", 22, KA_NAVY)
    sub = f"Portfolio Ownership  |  {pname}"
    if prop.get('entity_code'):
        sub += f"  ·  Entity {prop['entity_code']}"
    _center_line(doc, sub, 11, KA_BLUE, bold=False, after=10)
    title = ("Lease Abstract Compendium" if mode == 'full'
             else "Lease Abstract Compendium — Summary Edition")
    _center_line(doc, title, 18, KA_NAVY, after=2)
    _center_line(doc, f"{len(tenancies)} tenancies · "
                      f"{data['provision_total']:,} page-cited provisions",
                 11, KA_BLUE, bold=False, after=2)
    src_line = f"Generated {today} from the verified KA portfolio warehouse"
    if data.get('rent_roll_snapshot'):
        src_line += (f" · economics from the MRI rent roll, snapshot "
                     f"{data['rent_roll_snapshot']}")
    _center_line(doc, src_line, 9, GREY, bold=False, after=2)
    _red_rule(doc)
    banner = _center_line(
        doc, "COMPILED FROM VERIFIED, PAGE-CITED EXTRACTIONS — "
             "VERIFY AGAINST SOURCE INSTRUMENTS BEFORE LEGAL RELIANCE",
        9, KA_RED, after=2)
    banner.paragraph_format.space_before = Pt(8)

    # ── Provenance note ──
    doc.add_heading("How to Read This Compendium", level=1)
    intro = doc.add_paragraph()
    intro.add_run(
        "Each tenancy opens with a summary of its economics and key terms, "
        "followed by every extracted provision grouped by article/section, "
        "each with its source citation. Provisions flagged REFI IMPACT carry "
        "the aggregator's note on refinance relevance. Lease data comes from "
        "the page-cited KA portfolio warehouse (verified by its assertion "
        "suite); current rent and suite economics come from the canonical "
        "MRI rent-roll module. Where the two sources disagree the lease "
        "paper is shown and the rent roll is noted — flag, don't fabricate."
    ).font.size = Pt(10)

    # ── Tenancy index ──
    doc.add_heading("Tenancy Index", level=1)
    idx = doc.add_table(rows=1, cols=6)
    idx.style = "Table Grid"
    heads = ("Tenant", "Suite", "SF", "Expiration", "Status", "Provisions")
    for i, h in enumerate(heads):
        c = idx.rows[0].cells[i]
        _shade(c, NAVY_FILL)
        r = c.paragraphs[0].add_run(h)
        r.bold = True
        r.font.size = Pt(9)
        r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
    for t in tenancies:
        rr = t.get('rent_roll') or {}
        cells = idx.add_row().cells
        vals = (t['trade_name'] or t['tenant_key'],
                t.get('suite') or rr.get('suite') or '—',
                _fmt_sf(t.get('sf') or rr.get('sqft')) or '—',
                t.get('expiration') or rr.get('expiration') or '—',
                (t.get('status') or '—').title(),
                f"{len(t['provisions'])}"
                + (f"  ({t['refi_count']} refi)" if t['refi_count'] else ''))
        for i, v in enumerate(vals):
            r = cells[i].paragraphs[0].add_run(_clean(str(v)))
            r.font.size = Pt(9)

    # ── Per-tenancy sections ──
    for t in tenancies:
        rr = t.get('rent_roll') or {}
        doc.add_page_break()
        h = doc.add_heading(_clean(t['trade_name'] or t['tenant_key']), level=1)
        for run in h.runs:
            run.font.color.rgb = KA_NAVY

        pairs = [
            ("Legal tenant", t.get('legal_tenant')),
            ("Status", (t.get('status') or '').title()),
            ("Suite", t.get('suite') or rr.get('suite')),
            ("Square feet", _fmt_sf(t.get('sf') or rr.get('sqft'))),
            ("Lease expiration", t.get('expiration') or rr.get('expiration')),
            ("Current base rent (rent roll)",
             _fmt_money(rr.get('monthly_base_rent'))
             and _fmt_money(rr.get('monthly_base_rent')) + '/mo'),
            ("Rate PSF (rent roll)", rr.get('rate_psf')),
            ("Permitted use", t.get('use_type')),
            ("Guaranty", t.get('guaranty')),
            ("Renewal options", t.get('renewal_options')),
            ("Security deposit", t.get('security_deposit')),
        ]
        pairs = [(k, v) for k, v in pairs if v not in (None, '', '—')]
        if t.get('notes'):
            pairs.append(("Notes", t['notes']))
        _kv_table(doc, pairs)

        if rr.get('source_file'):
            cite = doc.add_paragraph()
            cr = cite.add_run(
                f"Rent-roll citation: {rr['source_file']}"
                + (f", p.{rr['source_page']}" if rr.get('source_page') else ''))
            cr.font.size = Pt(8)
            cr.font.color.rgb = GREY

        if not t['provisions']:
            p = doc.add_paragraph()
            r = p.add_run("No provision-level extraction for this tenancy.")
            r.italic = True
            r.font.color.rgb = GREY
            continue

        if mode == 'summary':
            doc.add_heading("Provision Index", level=2)
            ptbl = doc.add_table(rows=1, cols=3)
            ptbl.style = "Table Grid"
            for i, h_ in enumerate(("Provision", "Refi impact", "Source")):
                c = ptbl.rows[0].cells[i]
                _shade(c, NAVY_FILL)
                r = c.paragraphs[0].add_run(h_)
                r.bold = True
                r.font.size = Pt(8.5)
                r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
            for prov in t['provisions']:
                cells = ptbl.add_row().cells
                cells[0].paragraphs[0].add_run(
                    _clean(prov['category'] or '(uncategorized)')[:110]
                ).font.size = Pt(8.5)
                if _refi_flagged(prov):
                    rr_ = cells[1].paragraphs[0].add_run(
                        _clean(prov['refi_impact'].strip())[:160])
                    rr_.font.size = Pt(8.5)
                    rr_.font.color.rgb = KA_RED
                else:
                    cells[1].paragraphs[0].add_run('—').font.size = Pt(8.5)
                src = prov.get('source') or ''
                pgs = prov.get('source_pages') or ''
                cells[2].paragraphs[0].add_run(
                    _clean((src + (f" pp.{pgs}" if pgs else '')).strip()
                           or '(warehouse)')[:60]).font.size = Pt(8)
            continue

        doc.add_heading("Provisions", level=2)
        for prov in t['provisions']:
            cat = prov['category'] or '(uncategorized)'
            h3 = doc.add_heading(_clean(cat), level=3)
            for run in h3.runs:
                run.font.size = Pt(10.5)
                run.font.color.rgb = KA_NAVY

            # paragraphs, not tables — an order of magnitude faster on
            # 10K-provision properties, same reading experience
            detail = (prov['detail'] or '').strip()
            if len(detail) > 2500:
                detail = detail[:2500] + ' …'
            body = doc.add_paragraph()
            body.paragraph_format.left_indent = Inches(0.15)
            body.add_run(_clean(detail) or '—').font.size = Pt(9.5)

            if _refi_flagged(prov):
                rp = doc.add_paragraph()
                rp.paragraph_format.left_indent = Inches(0.15)
                rr_ = rp.add_run("REFI IMPACT: ")
                rr_.bold = True
                rr_.font.size = Pt(9)
                rr_.font.color.rgb = KA_RED
                rp.add_run(_clean(prov['refi_impact'].strip())).font.size = Pt(9)

            cite = doc.add_paragraph()
            cite.paragraph_format.left_indent = Inches(0.15)
            src = prov.get('source') or ''
            pgs = prov.get('source_pages') or ''
            cr = cite.add_run(_clean(
                "Source: " + (src if src else '(warehouse)')
                + (f", pp. {pgs}" if pgs else '')))
            cr.font.size = Pt(8)
            cr.font.color.rgb = GREY
            cite.paragraph_format.space_after = Pt(6)

    _footer(doc.sections[0],
            f"{pname} Lease Abstract Compendium · verified-source render")
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    doc.save(out_path)
    return {'out': out_path, 'tenancies': len(tenancies),
            'provisions': data['provision_total']}


def default_filename(property_name, mode='full'):
    safe = re.sub(r'[^A-Za-z0-9]+', '_', property_name or 'Property').strip('_')
    tag = '' if mode == 'full' else '_Summary'
    return (f"{safe}_Lease_Abstract_Compendium{tag}_"
            f"{datetime.date.today().isoformat()}.docx")
